### ISSUE TITLE
Gravitation Suite

### ISSUE THREAD

**Issue by Romz24** [Su5eD/GraviSuitePatcher#1]
Hi, there is a useful [Gravitation Suite](https://www.curseforge.com/minecraft/mc-mods/gravitation-suite) mod, but there are many bugs in it due to the fact that it has not been updated for a long time. Can you fix this?

- [If you put the advanced diamond drill in the miner, the server crashes](https://forum.industrial-craft.net/thread/13598-ic2-exp-1-10-x-gravitation-suite-v3-0-0-the-last-of-the-three/?postID=217734#post217734)
- When using the advanced diamond drill, the server sometimes crashes [link 1](https://forum.industrial-craft.net/thread/13598-ic2-exp-1-10-x-gravitation-suite-v3-0-0-the-last-of-the-three/?postID=218093#post218093), [link 2](https://forum.industrial-craft.net/thread/13598-ic2-exp-1-10-x-gravitation-suite-v3-0-0-the-last-of-the-three/?postID=218500#post218500)
_Current crash log - [crash-2021-07-04_14.10.09-server.txt](https://github.com/Su5eD/IC2-Patcher/files/6760014/crash-2021-07-04_14.10.09-server.txt)_
- Advanced diamond drill can not mine sand, gravel and dirt (_Blocks become invisible, you need to re-enter the game_)
- [Ultimate Lappack has the wrong crafting recipe](https://forum.industrial-craft.net/thread/13598-ic2-exp-1-10-x-gravitation-suite-v3-0-0-the-last-of-the-three/?postID=218184#post218184)
- Gravity Chestpiece does not protect against radiation [link 1](https://www.curseforge.com/minecraft/mc-mods/gravitation-suite?comment=68), [link 2](https://www.curseforge.com/minecraft/mc-mods/gravitation-suite?comment=74)

**Comment by Su5eD** [comment]
Is the Gravi Chestplate supposed to protect you from radiation? In the quantum armor, this is done by the helmet, not the chestplate. I've also tested this in 1.7.10, which *should* be bug free, and it didn't protect me from radiation either.

**Comment by Romz24** [comment]
On the [Russian Wikipedia](https://minecraft.fandom.com/ru/wiki/Gravitation_Suite) it is written that it has protection, of course it is possible this is a typo, but due to the fact that some users are complaining about a bug, I thought that it really should protect.

![image](https://user-images.githubusercontent.com/2458113/124773510-b0fc6300-df45-11eb-8d6d-b87b52102558.png)

**Comment by Su5eD** [comment]
I'll leave it non-protective for now. If you need the protection and already got the materials to make a quantum chestplate, making the helmet will be a piece of cake.

**Comment by Su5eD** [comment]
The patches are done. Once the CF project is approved, it will be available [here](https://www.curseforge.com/minecraft/mc-mods/gravitation-suite-patcher).

**Comment by cocutexyu** [comment]
> The patches are done. Once the CF project is approved, it will be available [here](https://www.curseforge.com/minecraft/mc-mods/gravitation-suite-patcher).

Hi! Messaged you in reddit, but now I can't even see your page there (something went wrong). Repeating the message here:
In actual IC2 version (for 1.12.2 — industrialcraft-2-2.8.222-ex112) you have to equip FULL quantum armor set to avoid radiation damage. When you change the quantum chestplate to gravichestplate − it causes you to taking damage by the radiation effect (and dying very fast). Same issue goes to Advanced Solar Panels addon: helmets from there (based on quantum helmet) have no radiation resistance.

I don't know about damage reduction (relative to a regular quantum chestplate), but if there are difference in stats too, it would be nice to bring them to a single value (as it should be). The Gravity Chestplate can't possibly be any worse than the Quantum Chest, given the crafting recipe.

**Comment by pawel630** [comment]
@cocutexyu Exactly, in ic2 the whole QuantumSuit set protects you from receiving radiation in the first place, and the helmet just removes the effect if you do end up getting it, which results in the helmet instantly losing power cause it has to constantly remove the radiation effect thanks to the GravitationChestPlate not shielding you from radiation, it's even stated on the Gravitation Suite page that the GravitationChestPlate "Contains all the features of quantum body armour.". As for the solar helmets the lack of radiation protection is intended, it's stated as a trade-off on the mod page

**Comment by cocutexyu** [comment]
@pawel630 So that's what we're talking about, it turns out that the quote «Gravitation Chest Plate contains all the features of quantum body armor» is incorrect, cause a quantum chest plate (complete with the rest of the quantum armor set) provides a radiation protection, while a Gravitation Chest Plate complete with the rest of the quantum armor doesn't do the same. Will this bug be fixed?
